name = "rrb-hackathon-backend"
main = "src/index.ts"
compatibility_date = "2022-12-03"

[vars]
COHERE_ENDPOINT = "https://api.cohere.ai/generate"
COHERE_VERSION = "2021-11-08"
FRONTEND_ENDPOINT = "https://zodiac.tarinyoom.io"
